services:
  mongodb:
    image: mongo:latest
    container_name: digital-attendance-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - attendance_mongodata:/data/db

volumes:
  attendance_mongodata:
